---
sidebar: sidebar 
permalink: nas.html 
keywords:  
summary:  
---
= NAS
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用这些 API 调用来管理集群和 SVM 的 CIFS 和 NFS 设置。



==== 审核日志重定向

您可以将 NAS 审核事件重定向到特定 SVM 。此资源类型是 ONTAP 9.8 的新增功能。



==== Audit

可以为 SVM 记录某些 CIFS 和 NFS 事件，这有助于提高安全性。此资源类型是在 ONTAP 9.6 中引入的。



==== CIFS 主目录搜索路径

可以在 CIFS 服务器上为 SMB 用户创建主目录，而无需为每个用户创建单独的 SMB 共享。主目录搜索路径是从 SVM 根目录开始的一组绝对路径。此资源类型是在 ONTAP 9.6 中引入的。



==== CIFS 服务

CIFS 服务器的核心配置。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。



==== CIFS 会话

您可以使用此 API 检索有关 CIFS 会话的详细信息。此资源类型是在 ONTAP 9.8 REST API 中引入的，并在 ONTAP 9.9 中进行了增强。



==== CIFS 共享

在 CIFS 服务器上定义的 SMB 共享。此资源类型是在 ONTAP 9.6 中引入的。



==== CIFS 共享 ACL

访问控制列表（ ACL ）用于控制对 CIFS 共享上的文件夹和文件的访问。此资源类型是在 ONTAP 9.6 中引入的。



==== CIFS UNIX 符号链接映射

CIFS 和 UNIX 客户端均可访问同一数据存储库。当 UNIX 客户端创建符号链接时，这些映射会引用其他文件或文件夹来支持 CIFS 客户端。此资源类型是在 ONTAP 9.6 中引入的。



==== 文件访问跟踪

您可以使用这些 API 调用来跟踪对特定文件的访问。此资源类型是 ONTAP 9.8 的新增功能。



==== 文件安全权限

您可以使用这些 API 调用来显示为 Windows 或 Unix 用户授予的特定文件或文件夹的有效权限。您还可以管理 NTFS 文件安全性和审核策略。此资源类型是在 ONTAP 9.8 REST API 中引入的，并在 ONTAP 9.9 中得到了显著增强。



==== fpolicy

FPolicy 是一个文件访问通知框架，用于监控和管理 SVM 上的文件访问事件。此资源类型是在 ONTAP 9.6 中引入的。



==== FPolicy 引擎

通过 FPolicy 引擎，您可以确定接收文件访问通知的外部服务器。此资源类型是在 ONTAP 9.6 中引入的。



==== FPolicy 事件

用于确定如何监控文件访问以及生成哪些事件的配置。此资源类型是在 ONTAP 9.6 中引入的。



==== FPolicy 策略

FPolicy 框架要素的容器，包括 FPolicy 引擎和事件。此资源类型是在 ONTAP 9.6 中引入的。



==== NFS 连接的客户端

您可以显示已连接客户端的列表及其连接详细信息。此资源类型是在 ONTAP 9.7 中引入的。



==== NFS 导出策略

包含用于描述 NFS 导出的规则的策略。此资源类型是在 ONTAP 9.6 中引入的。



==== NFS Kerberos 接口

Kerberos 接口的配置设置。此资源类型是在 ONTAP 9.6 中引入的。



==== NFS Kerberos 域

Kerberos 域的配置设置。此资源类型是在 ONTAP 9.6 中引入的。



==== NFS 服务

NFS 服务器的核心配置。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。



==== Vscan

一种安全功能，用于保护您的数据免受病毒和其他恶意代码的影响。此资源类型是在 ONTAP 9.6 中引入的。



==== Vscan 实时策略

Vscan 策略允许在客户端访问时主动扫描文件对象。此资源类型是在 ONTAP 9.6 中引入的。



==== Vscan 按需策略

Vscan 策略允许根据需要或设置的计划立即扫描文件对象。此资源类型是在 ONTAP 9.6 中引入的。



==== Vscan 扫描程序池

一组属性，用于管理 ONTAP 与外部病毒扫描服务器之间的连接。此资源类型是在 ONTAP 9.6 中引入的。



==== Vscan 服务器状态

外部病毒扫描服务器的状态。此资源类型是在 ONTAP 9.6 中引入的。
