---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP 自动化文档
    url: "/index.html"
  - title: 新增功能
    url: "/whats_new.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
