---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP 自动化文档
    url: "/index.html"
  - title: 新增功能
    url: "/whats_new.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: migrate
  - section: reference
  - section: additional
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 发行说明
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: ONTAP 自动化选项
      url: "/get-started/ontap_automation_options.html"
    - title: 您的第一次API调用
      url: "/get-started/first_call.html"
  - title: ONTAP REST API
    links:
    - title: REST 实施详细信息
      url: "/rest/rest_web_services_foundation.html"
    - title: 其他注意事项
      url: "/rest/object_references_and_access.html"
    - title: REST资源摘要
      url: "/resources/overview_categories.html"
    - title: API 参考
      url: "/reference/api_reference.html"
  - title: 自动化
    links:
    - title: Python 客户端库
      url: "/python/overview_pcl.html"
  - title: 迁移到REST API
    links:
    - title: 已取消ONTAPI
      url: "/migrate/overview.html"
    - title: ONTAPI到REST映射
      url: "/migrate/mapping.html"
    - title: 性能计数器
      url: "/migrate/performance-counters.html"
    - title: 博客文章
      url: "/migrate/blogs.html"
  - title: 知识和支持
    links:
    - title: 其他资源
      url: "/additional/resources.html"
    - title: NetApp DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 文档
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select 文档
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
