---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr,fr-fr,de-de
sidebar:
  entries:
  - title: ONTAP 自动化文档
    url: "/index.html"
  - section: rn
  - section: get-started
  - section: rest
  - section: workflows
  - section: manage
  - section: python
  - section: reference
  - section: automate
  - section: migrate
  - section: additional
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 发行说明
      url: "/rn/whats_new.html"
    - title: ONTAP 自动化选项
      url: "/get-started/ontap_automation_options.html"
    - title: 准备使用 REST API
      url: "/get-started/prepare.html"
    - title: 大家好
      url: "/get-started/hello_world.html"
  - title: ONTAP REST API
    links:
    - title: REST 实施详细信息
      url: "/rest/rest_web_services_foundation.html"
    - title: 其他注意事项
      url: "/rest/object_references_and_access.html"
    - title: REST 资源摘要
      url: "/resources/overview_categories.html"
    - title: API 参考
      url: "/reference/api_reference.html"
  - title: 自动化
    links:
    - title: Python 客户端库
      url: "/python/overview_pcl.html"
    - title: ONTAP 和 Ansible
      url: "/automate/ontap_ansible.html"
    - title: 自动化博客
      url: "/automate/blogs.html"
  - title: 更多资源
    links:
    - title: 获取更多信息
      url: "/additional/get_more_information.html"
    - title: NetApp DevNet
      url: https://devnet.netapp.com/restapi.php
    - title: ONTAP 9 文档
      url: https://docs.netapp.com/us-en/ontap/
    - title: ONTAP Select 文档
      url: https://docs.netapp.com/us-en/ontap-select/
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: 所有ONTAP 产品文档
