---
sidebar: sidebar 
permalink: security.html 
keywords:  
summary:  
---
= 安全性
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
这些 API 调用可用于管理集群和 SVM 安全设置。



==== 集群安全性

您可以检索集群范围安全性的详细信息并更新某些参数。此资源类型是在 ONTAP 9.7 中引入的，并在 ONTAP 9.8 中进行了更新。



==== —帐户

集群和 SVM 有一组用户帐户。此资源类型是在 ONTAP 9.6 中引入的。



==== 帐户名称

范围内的用户帐户的配置。此资源类型是在 ONTAP 9.6 中引入的。



==== Audit

用于确定审核日志文件中记录的内容的设置。此资源类型是在 ONTAP 9.6 中引入的。



==== 审核目标

这些设置控制将审核日志信息转发到远程系统或 Splunk 服务器的方式。此资源类型是在 ONTAP 9.6 中引入的。



==== 审核消息

您可以检索审核日志消息。此资源类型是在 ONTAP 9.6 中引入的。



==== Active Directory 代理

您可以在 Active Directory 服务器上管理 SVM 帐户信息。此资源类型是在 ONTAP 9.7 中引入的。



==== LDAP 身份验证

这些 API 调用用于检索和管理集群 LDAP 服务器配置。此资源类型是在 ONTAP 9.6 中引入的。



==== NIS 身份验证

这些设置用于检索和管理集群 NIS 服务器配置。此资源类型是在 ONTAP 9.6 中引入的。



==== SAML 服务提供程序

您可以显示和管理 SAML 服务提供程序的配置。此资源类型是在 ONTAP 9.6 中引入的。



==== 密码身份验证

这包括用于更改用户帐户密码的 API 调用。此资源类型是在 ONTAP 9.6 中引入的。



==== 公有密钥身份验证

您可以使用这些 API 调用为用户帐户配置公有密钥。此资源类型是在 ONTAP 9.7 中引入的。



==== AWS KMS

通过这组 API 调用，您可以使用 Amazon Web Services 密钥管理服务来存储 ONTAP 加密密钥。此资源类型是 ONTAP 9.8 的新增功能。



==== Azure 密钥存储

通过这组 API 调用，您可以使用 Azure 密钥存储来存储 ONTAP 加密密钥。此资源类型是 ONTAP 9.8 的新增功能。



==== 证书

API 调用可用于安装，显示和删除 ONTAP 使用的证书。此资源类型是在 ONTAP 9.7 中引入的。



==== GCP KMS

通过这组 API 调用，您可以使用 Google 云平台密钥管理服务来存储和管理 ONTAP 加密密钥。此资源类型最初是在 ONTAP 9.8 REST API 中引入的。但是，此功能已经过重新设计，因此在 ONTAP 9.9 中被视为新增资源类型。



==== IPsec

Internet 协议安全性（ Internet Protocol Security ， IPsec ）是一套协议，可通过底层 IP 网络在两个端点之间提供安全性。此资源类型是 ONTAP 9.8 的新增功能。



==== IPsec 策略

您可以使用这组 API 调用来管理对 IPsec 部署有效的策略。此资源类型是 ONTAP 9.8 的新增功能。



==== IPsec 安全关联

您可以使用这组 API 调用来管理对 IPsec 部署有效的安全关联。此资源类型是 ONTAP 9.8 的新增功能。



==== 密钥管理器

密钥管理器允许 ONTAP 中的客户端模块安全地存储密钥。此资源类型是在 ONTAP 9.6 中引入的，并针对 ONTAP 9.7 进行了更新。



==== 登录消息

用于显示和管理 ONTAP 使用的登录消息。此资源类型是在 ONTAP 9.6 中引入的。



==== 角色

这些角色提供了一种向用户帐户分配权限的方法。此资源类型是在 ONTAP 9.6 中引入的。



==== 角色实例

角色的特定实例。此资源类型是在 ONTAP 9.6 中引入的。



==== 角色实例的特权

管理特定角色的特权。此资源类型是在 ONTAP 9.6 中引入的。



==== SSH

通过这些调用，您可以设置 SSH 配置。此资源类型是在 ONTAP 9.7 中引入的。
