---
sidebar: sidebar 
permalink: storage.html 
keywords:  
summary:  
---
= 存储
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用这些 API 调用来管理物理和逻辑存储。



==== 聚合

聚合包含一个或多个 RAID 组。此资源类型是在 ONTAP 9.6 中引入的。



==== 聚合丛

聚合中 WAFL 存储的物理副本。此资源类型是在 ONTAP 9.6 中引入的。



==== 聚合指标

您可以检索特定聚合的历史指标数据。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。



==== 网桥

您可以检索集群中的网桥。此资源类型是在 ONTAP 9.9 中引入的。



==== Disks

集群中的物理磁盘。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 和 9.8 中进行了更新。



==== FlexCache.

此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== FlexCache 起源

FlexCache 是原始卷的永久性缓存。此资源类型最初是在 ONTAP 9.6 中推出的。ONTAP 9.9 REST API 增强了支持，支持通过 HTTP 修补方法进行修改。



==== 受监控的文件

您可以指定特定文件以进行额外监控。此资源类型是 ONTAP 9.8 的新增功能。



==== 端口

集群的存储端口。此资源类型是在 ONTAP 9.6 中引入的。



==== QoS 策略

服务质量策略配置。此资源类型是在 ONTAP 9.6 中引入的。



==== qtree

您可以使用这些 API 调用来管理 qtree ， qtree 是一种按逻辑划分的文件系统。此资源类型是在 ONTAP 9.6 中引入的。



==== 配额报告

报告配额，这是一种用于限制或跟踪文件或空间使用量的技术。此资源类型是在 ONTAP 9.6 中引入的。



==== 配额规则

用于强制实施配额的规则。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。



==== 磁盘架

集群中的磁盘架。此资源类型是在 ONTAP 9.6 中引入的。



==== Snapshot 策略

快照是根据策略创建的。此资源类型是在 ONTAP 9.6 中引入的。



==== Snapshot 计划

您可以控制快照计划。此资源类型在 ONTAP 9.8 中进行了新的重新设计。



==== 交换机

您可以检索集群中的交换机。此资源类型是在 ONTAP 9.9 中引入的。



==== 磁带设备

您可以检索集群中的磁带设备。此资源类型是在 ONTAP 9.9 中引入的。



==== 卷效率策略

您可以使用这些 API 调用来配置应用于整个卷的效率。此资源类型是 ONTAP 9.8 的新增功能。



==== Volumes

逻辑容器用于向客户端提供数据。此资源类型最初是在 ONTAP 9.6 REST API 中引入的。在 ONTAP 9.9 中， API 中使用的许多参数值都得到了显著扩展，包括用于空间管理的参数值。



==== 卷文件

您可以检索卷上特定目录的文件和目录列表。此资源类型是在 ONTAP 9.7 中引入的，并在 ONTAP 9.8 中进行了更新。



==== 卷快照

卷的快照。此资源类型是在 ONTAP 9.6 中引入的。
