---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new features, new in release 
summary: 每个ONTAP版本都会更新ONTAP REST API、为您提供新功能、增强功能和错误修复。 
---
= ONTAP REST API的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
每个ONTAP版本都会更新ONTAP REST API、为您提供新功能、增强功能和错误修复。


TIP: 您应查看 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["《 ONTAP 发行说明》"^]以了解其他信息、包括已知限制或问题。另请参见 link:api-changes.html["对ONTAP REST API调用进行的更改"] 、了解可能影响自动化软件的任何更改。



== ONTAP 9.18.1

ONTAP 9.18.1 版本通过十三个新的 API 调用继续扩展 ONTAP REST API 的功能。这些增强功能主要侧重于安全性，但也包括与存储管理相关的改进。

安全性:: ONTAP 9.18.1 REST API 引入了多项安全增强功能。您可以使用新的群集网络终结点来显示和更新群集网络安全配置，包括证书管理。此外，您可以管理 NVLog 流量的 HA 网络的安全配置。自主勒索软件防护 (ARP) 已得到增强，以支持自动启用配置的显示和更新。
存储:: NetApp FlexCache是源卷的持久缓存。它支持扇出，因此可以从单个源卷创建多个FlexCache 。REST API 支持检索缓存实例和源卷之间的连接状态。




== ONTAP 9.17.1

ONTAP 9.17.1 版本继续扩展ONTAP REST API 的功能，新增了近二十个 API 调用。此版本主要侧重于安全性增强，并对中介处理、NMVe 子系统和应用程序容器进行了额外更新。

安全性:: ONTAP 9.17.1 REST API 引入了四项主要安全功能。ONTAPONTAP(JIT) 权限提升是对基于角色的访问控制 (RBAC) 的增强。集群管理员可以请求临时提升现有角色权限，从而允许访问特权命令。该功能包含一组强大的配置选项。新增了对 OpenStack Barbican 密钥管理器的支持。此 KMS 用于维护NetApp卷加密 (NVE) 的密钥。ONTAPONTAP包含针对 SAN 卷的自主勒索软件防护 (ARP)。详细的 ARP 熵统计信息可通过 REST API 获取。此外，还添加了多个 API 调用来管理集群的 SAML 默认元数据配置。
集群中介:: 您可以使用ONTAP REST API 对NetApp控制台云服务执行 ping 操作。您还可以使用现有端点的 PATCH 方法修改特定中介器的配置。
NVMe:: NVMe 子系统维护一组 NVMe 连接主机的配置状态和命名空间访问控制。使用ONTAP 9.17.1，您可以使用现有端点的 PATCH 方法修改 NVMe 子系统。
应用程序容器:: 应用程序容器是ONTAP 9.17.1 中的新功能，支持配置一个或多个存储对象。您可以配置客户端访问存储所需的策略和规则。此外，还可以配置FlexCache卷。




== ONTAP 9.16.1.

API.16.1包含20多个新的ONTAP 9调用、这些调用将继续扩展ONTAP REST API的功能。这些增强功能主要侧重于安全性、但也包括对指标和存储分段管理的改进。


NOTE: 公开给NetApp ASA R2系统(ASA A1K、ASA A70和ASA A90)用户的ONTAP REST API与所有其他FAS、AFF和ASA系统提供的REST API不同。有关详细信息、请参见 https://docs.netapp.com/us-en/asa-r2/learn-more/rest-api-support.html["ASA R2系统的REST API支持"^] 。

Microsoft Entra ID的OAuth2.0支持:: OAuth.14.1首次引入了ONTAP 9 2.0支持。OAuth.16.1增强了ONTAP 9 2.0功能、可支持具有标准OAuth2.0声明的Microsoft Entra ID授权服务器(以前称为Azure AD)。包括两个主要功能、如下所述。
使用组作为UUID的OAuth2.0:: 通过两项新功能和十个新API调用、可支持基于UUID模式值的Entra ID标准组声明：
+
--
* 组UUID到组名称映射(`/security/groups`)
* UUID组到角色映射(`/security/group/role-mapping`()


--
具有外部角色的OAuth2.0:: 外部角色在定义给ONTAP的OAuth2.0标识提供程序中定义。您可以创建和管理这些外部角色与ONTAP角色之间的映射关系。添加了五个新的API调用。
Web身份验证:: Web身份验证(WebAuthn)是一种Web标准、用于根据公共密钥加密对用户进行安全身份验证。借助ONTAP、它支持通过System Manager和ONTAP REST API管理防钓鱼的MFA。在多个端点添加了七个新的API调用。
自主的防兰软件保护版本控制和更新:: 添加了两个API调用以及一个新端点、用于管理ONTAP使用的自主防兰软件包。您可以显示的版本并更新自主防兰软件包。
qtree指标:: ONTAP 9 16.1提供了一个可选的qtree扩展性能监控功能。启用此功能后、ONTAP会捕获其他数据、包括延迟指标和历史数据。添加了一个新端点、可用于检索此性能数据。
S3存储分段快照:: 添加了四个新的API调用、用于创建和管理S3存储分段的快照。每个快照都是创建快照时存储分段的映像。




== ONTAP 9.15.1.

API.15.1将继续扩展ONTAP REST ONTAP 9的功能、包括支持两项新功能。

基于TLS的NFS:: 此功能提供了三个新端点。您可以通过问题描述这些API调用检索基于TLS的所有NFS接口、通过UUID检索特定接口以及更新TLS接口的配置属性。这些API调用共同提供了一组等效的 `vserver nfs tls interface` CLI命令。



CAUTION: 基于TLS的NFS在ONTAP 9.151中提供公开预览版。作为预览选项、使用ONTAP 9.15.1的生产工作负载不支持此功能。

Windows备份应用程序和Unix模式符号链接:: 当Windows备份应用程序遇到Unix模式的符号链接(符号链接)时、将遍历该链接、ONTAP将返回数据并进行备份。从ONTAP 9.15.1开始、您还可以选择备份符号链接、而不是其所指向的数据。这可以提供多种优势、包括提高备份应用程序的性能。已更新此端点 `/protocols/cifs/services/{svm.uuid}` 、以便在对象中包含新参数 `backup-symlink-enabled` `options` 。




== ONTAP 9.14.1

ONTAP 9.14.1版包含超过30个新的API调用、这些调用继续扩展ONTAP REST API的功能。这些端点支持多项新的ONTAP功能以及对现有功能的更新。此版本主要侧重于安全性增强功能、但也包括对NAS、QoS和性能指标的改进。

安全性:: ONTAP 9.14.1中引入了两项主要的安全功能。开放式授权(OAuth2.0)是一种基于令牌的框架、可用于限制对ONTAP存储资源的访问。您可以将其用于通过REST API访问ONTAP的客户端。可以使用任何ONTAP管理界面(包括REST API)执行配置。ONTAP 9.14.1版还支持Cisco Duo、可为SSH登录提供双因素身份验证。您可以将Duo配置为在ONTAP集群或SVM级别运行。除了这两项新功能之外、还添加了多个端点、以提高对密钥存储库的控制力。
FPolicy永久性存储:: FPolicy为ONTAP策略管理提供了一个平台。它为各种组件或元素(例如事件和策略引擎)提供了一个容器。现在、您可以使用REST API为ONTAP FPolicy配置和事件配置和管理永久性存储。每个SVM都可以有一个永久性存储、该存储可供SVM中的多个策略共享。
QoS选项:: 引入了两个端点、可用于检索和设置集群的QoS选项。例如、您可以为后台任务预留一定百分比的可用系统处理资源。
性能指标:: ONTAP维护有关系统运行特征的统计信息。此信息以表格和行组成的数据库格式显示。在ONTAP 9.14.1中、还会在多个资源类别中添加其他指标数据、包括光纤通道、iSCSI、LUN和NVMe。这些附加指标数据继续使ONTAP REST API与Data ONTAP API (ONTAPI或ZAPI)更接近。
其他增强功能:: 根据您的环境、还有一些其他增强功能可能会很有用。这些新的端点改进了对SAN启动程序的访问、并控制了主机缓存设置、还支持访问各个AutoSupport消息。




== ONTAP 9.13.1

ONTAP 9.13.1通过20多个新的API调用不断扩展ONTAP REST API的功能。这些端点支持新的ONTAP 功能以及对现有功能的增强功能。此版本重点改进了安全性、资源管理、增强的SVM配置选项和性能指标。

资源标记:: 您可以使用标记对REST API资源进行分组。您可以执行此操作来关联特定项目或组织组中的相关资源。使用标记有助于更有效地组织和跟踪资源。
一致性组:: ONTAP 9.13.1会继续扩展性能计数器数据的可用性。现在、您可以访问此类统计信息来跟踪一致性组的历史性能和容量。此外、还提供了一些增强功能、可用于配置和管理一致性组之间的父子关系。
每个SVM的DNS配置:: 现有DNS端点已进行扩展、可对单个SVM执行DNS域和服务器配置。
EMS角色配置:: 现有的EMS支持功能已进行扩展、可用于管理角色以及分配给这些角色的访问控制配置。这样、便可根据角色配置限制或筛选事件和消息。
安全性:: 您可以使用REST API为使用SSH登录和访问ONTAP 的帐户配置基于时间的一次性密码(TOTP)配置文件。此外、密钥管理器端点已进行扩展、可从指定的密钥管理服务器执行还原操作。
每个SVM的CIFS配置:: 现有CIFS端点已进行扩展、可以更新特定SVM的配置。
S3存储分段规则:: 现有S3存储分段端点已进行扩展、可包含规则定义。每个规则都是一个列表对象、用于定义要对存储分段中的对象执行的一组操作。这些规则可以让您更好地管理S3存储分段的生命周期。




== ONTAP 9.12.1

ONTAP 9.12.1继续扩展ONTAP REST API的功能、新增了40多个API调用。这些端点支持新的ONTAP 功能以及对现有功能的增强功能。此版本重点介绍了安全性和NAS功能的改进。

安全性增强功能:: Amazon Web Services包括一项密钥管理服务、可为密钥和其他机密提供安全存储。您可以通过REST API访问此服务、以使ONTAP 能够将其加密密钥安全地存储在云中。此外、您还可以创建和列出用于NetApp存储加密的身份验证密钥。
Active Directory:: 您可以管理为ONTAP 集群定义的Active Directory帐户。其中包括创建新帐户以及显示、更新和删除帐户。
CIFS组策略:: REST API已进行了增强、可支持创建和管理CIFS组策略。配置信息可通过应用于所有或特定SVM的组策略对象进行访问和管理。




== ONTAP 9.11.1

ONTAP 9.11.1继续扩展ONTAP REST API的功能、新增了近100个API调用。这些端点支持新的ONTAP 功能以及对现有功能的增强功能。

粒度RBAC:: ONTAP 基于角色的访问控制(Role-Based Access Control、RBAC)功能已得到增强、可提供更多粒度。您可以根据需要通过REST API使用传统角色或创建新的自定义角色。每个角色都与一个或多个权限相关联、每个权限都标识一个REST API调用或命令行界面命令以及访问级别。为REST角色提供了新的访问级别、例如 `read_create` 和 `read_modify`。此增强功能可与Data ONTAP API (ONTAPI或ZAPI)实现奇偶校验、并支持客户迁移到REST API。请参见 link:rest/rbac_overview.html["RBAC 安全性"] 有关详细信息 ...
性能计数器:: 先前版本的ONTAP 保留了有关系统运行特征的统计信息。在9.11.1版中、此信息已得到增强、现在可通过REST API获得。管理员或自动化流程可以访问数据以确定系统性能。计数器管理器子系统维护的统计信息以数据库格式使用表和行显示。此增强功能使ONTAP REST API更接近与Data ONTAP API (ONTAPI或ZAPI)的奇偶校验。
聚合管理:: ONTAP 存储聚合的管理已得到增强。您可以使用更新后的REST端点联机和脱机移动聚合、以及管理备用磁盘。
IP子网功能:: ONTAP 网络功能已扩展、包括对IP子网的支持。通过REST API、您可以配置和管理ONTAP 集群中的IP子网。
多个管理员验证:: 多管理员验证功能提供了一个灵活的授权框架、用于保护对ONTAP 命令或操作的访问。您可以定义用于标识受限命令的规则。当用户请求访问特定命令时、可以根据需要由多个ONTAP 管理员授予批准权限。
SnapMirror增强功能:: SnapMirror功能在计划等多个方面得到了增强。SnapVault 关系奇偶校验已添加到与ONTAP 9.11.1的DP关系中。此外、REST API提供的限制功能已与Data ONTAP API (ONTAPI或ZAPI)达到奇偶校验。与此相关、可支持创建和管理批量Snapshot副本。
存储池:: 添加了多个端点、用于访问ONTAP 存储池。支持在集群中创建和列出存储池、以及按ID更新和删除特定池。
名称服务缓存支持:: ONTAP 名称服务已得到增强、可支持缓存、从而提高性能和故障恢复能力。现在、可以通过REST API访问名称服务缓存的配置。可以在多个级别应用设置、包括主机、UNIX用户、UNIX组和网络组。
ONTAPI报告工具:: ONTAPI报告工具可帮助客户和合作伙伴确定其环境中的ONTAPI使用情况。此工具可为计划从ONTAPI迁移到ONTAP REST API的客户提供有价值的见解。




== ONTAP 9.10.1

ONTAP 9.10.1 将继续扩展 ONTAP REST API 的功能。添加了 100 多个新端点，以支持新的 ONTAP 功能以及对现有功能的增强。下面简要介绍了 REST API 增强功能。

应用程序一致性组:: 一致性组是指在执行快照等特定操作时组合在一起的一组卷。此功能可扩展单卷操作在一组卷中隐式的崩溃一致性和数据完整性。它对于大型多卷工作负载应用程序非常重要。
SVM 迁移:: 您可以将 SVM 从源集群迁移到目标集群。新端点可提供完全控制，包括暂停，恢复，检索状态和中止迁移操作的功能。
文件克隆和管理:: 卷级文件克隆和管理已得到增强。新的 REST 端点支持文件移动，复制和拆分操作。
改进了 S3 审核:: 对 S3 事件的审核是一项安全改进，可用于跟踪和记录某些 S3 事件。可以为每个存储分段的每个 SVM 设置 S3 审核事件选择器。
勒索软件防护:: ONTAP 会检测可能包含勒索软件威胁的文件。您可以检索这些可疑文件的列表并将其从卷中删除。
其他安全增强功能:: 有几项常规的安全增强功能可扩展现有协议并引入新功能。已对 IPsec ，密钥管理， SSH 配置和文件权限进行了改进。
CIFS 域和本地组:: 已在集群和 SVM 级别添加对 CIFS 域的支持。您可以检索域配置以及创建和删除首选域控制器。
扩展了卷分析:: 卷分析和指标已通过其他端点进行扩展，以支持顶级文件，目录和用户。
支持增强功能:: 通过多项新功能增强了支持。自动更新可以通过下载并应用最新的软件更新来使您的ONTAP系统保持最新。您还可以检索和管理节点生成的内存核心转储。




== ONTAP 9.9.1

ONTAP 9.9.1 将继续扩展 ONTAP REST API 的功能。现有 ONTAP 功能具有新的 API 端点，包括 SAN 端口集和 SVM 文件目录安全性。此外，还添加了端点来支持新的 ONTAP 9.9.1 功能和增强功能。相关文档也进行了改进。下面简要介绍了这些增强功能。

将 ONTAPI 映射到 ONTAP 9 REST API:: 为了帮助您将 ONTAP 自动化代码过渡到 REST API ， NetApp 提供了 API 映射文档。此参考包括 ONTAPI 调用列表以及每个调用的 REST API 等效项。此映射文档已进行更新，以包含新的 ONTAP 9.9.1 API 端点。请参见 link:migrate/mapping.html["ONTAPI 到 REST API 映射"] 有关详细信息 ...
API 端点，用于新的 ONTAP 9.9.1 核心功能:: REST API 中增加了对通过 ONTAPI 不可用的新 ONTAP 9.9.1 功能的支持。其中包括对嵌套 igroup 和 Google Cloud 密钥管理服务的支持。
改进了从 ONTAPI 过渡到 REST 的支持:: 现在，更多传统 ONTAPI 调用都具有相应的 REST API 等效项。其中包括本地 Unix 用户和组，无需客户端即可管理 NTFS 文件安全性， SAN 端口集以及卷空间属性。更新后的 ONTAPI to REST 映射文档也会包含这些更改。
增强的联机文档:: 现在， ONTAP 联机文档参考页面包含一些标签，用于指示引入每个 REST 端点或参数时的 ONTAP 版本，包括 ONTAP 9.1.1 中的新端点或参数。




== ONTAP 9.8

ONTAP 9™8提供了多种新功能，可增强您自动部署和管理ONTAP存储系统的能力。此外，我们还改进了对帮助从原有 ONTAPI 过渡到 REST 的支持。

将 ONTAPI 映射到 ONTAP 9 REST API:: 为了帮助您更新 ONTAPI 自动化， NetApp 提供了一个需要一个或多个输入参数的 ONTAPI 调用列表，以及这些调用与等效的 ONTAP 9 REST API 调用的映射。请参见 link:migrate/mapping.html["ONTAPI 到 REST API 映射"] 有关详细信息 ...
用于新ONTAP 9 8功能的API端点:: REST API增加了对不能通过ONTAPI获得的新ONTAP 9 8功能的支持。其中包括对ONTAP S3存储分段和服务、SnapMirror主动同步(以前称为SnapMirror业务连续性)和文件系统分析的REST API支持。
扩展了对增强安全性的支持:: 通过支持 Azure 密钥存储， Google Cloud 密钥管理服务， IPsec 和证书签名请求等多种服务和协议，安全性得到了增强。
增强功能可提高精简性:: ONTAP 9.8 可使用 REST API 提供更高效，更现代化的工作流。例如、现在可以为多种不同类型的固件提供一键式固件更新。
增强的联机文档:: ONTAP联机文档页面包含一些标签、用于指示ONTAP发行版中引入的每个REST端点或参数、包括9.8中的新增功能。
改进了从 ONTAPI 过渡到 REST 的支持:: 现在，更多传统 ONTAPI 调用具有相应的 REST API 等效项。此外，我们还提供了一些文档来帮助您确定应使用哪个 REST 端点来取代现有的 ONTAPI 调用。
扩展了性能指标:: REST API 的性能指标已扩展，包括多个新的存储和网络对象。




== ONTAP 9.7

ONTAP 9.7 通过引入三个新的资源类别来扩展 ONTAP REST API 的功能范围，每个资源类别都有多个 REST 端点：

* NDMP
* 对象存储
* SnapLock


ONTAP 9.7 还会在多个现有资源类别中引入一个或多个新的 REST 端点：

* 集群
* NAS
* 网络
* NVMe
* SAN
* 安全性
* 存储
* 支持




== ONTAP 9.6

ONTAP 9.6 极大地扩展了最初在 ONTAP 9.4 中引入的 REST API 支持。ONTAP 9.6 REST API 支持大多数 ONTAP 配置和管理任务。

ONTAP 9.6 中的 REST API 包括以下关键方面以及更多方面：

* 集群设置
* 协议配置
* 配置
* 性能监控
* 数据保护
* 应用程序感知型数据管理

