---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= ONTAP REST API 和自动化的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 会定期更新 ONTAP REST API ，为您提供新功能，增强功能和错误修复。



== ONTAP 9.10.1

ONTAP 9.10.1 将继续扩展 ONTAP REST API 的功能。添加了 100 多个新端点，以支持新的 ONTAP 功能以及对现有功能的增强。下面简要介绍了 REST API 增强功能。

应用程序一致性组:: 一致性组是指在执行快照等特定操作时组合在一起的一组卷。此功能可扩展单卷操作在一组卷中隐式的崩溃一致性和数据完整性。它对于大型多卷工作负载应用程序非常重要。
SVM 迁移:: 您可以将 SVM 从源集群迁移到目标集群。新端点可提供完全控制，包括暂停，恢复，检索状态和中止迁移操作的功能。
文件克隆和管理:: 卷级文件克隆和管理已得到增强。新的 REST 端点支持文件移动，复制和拆分操作。
改进了 S3 审核:: 对 S3 事件的审核是一项安全改进，可用于跟踪和记录某些 S3 事件。可以为每个存储分段的每个 SVM 设置 S3 审核事件选择器。
勒索软件防护:: ONTAP 会检测可能包含勒索软件威胁的文件。您可以检索这些可疑文件的列表并将其从卷中删除。
其他安全增强功能:: 有几项常规的安全增强功能可扩展现有协议并引入新功能。已对 IPsec ，密钥管理， SSH 配置和文件权限进行了改进。
CIFS 域和本地组:: 已在集群和 SVM 级别添加对 CIFS 域的支持。您可以检索域配置以及创建和删除首选域控制器。
扩展了卷分析:: 卷分析和指标已通过其他端点进行扩展，以支持顶级文件，目录和用户。
支持增强功能:: 通过多项新功能增强了支持。自动更新可以通过下载并应用最新的软件更新来使 ONTAP 系统保持最新。您还可以检索和管理节点生成的内存核心转储。




== ONTAP 9.9.1

ONTAP 9.9.1 将继续扩展 ONTAP REST API 的功能。现有 ONTAP 功能具有新的 API 端点，包括 SAN 端口集和 SVM 文件目录安全性。此外，还添加了端点来支持新的 ONTAP 9.9.1 功能和增强功能。相关文档也进行了改进。下面简要介绍了这些增强功能。

将 ONTAPI 映射到 ONTAP 9 REST API:: 为了帮助您将 ONTAP 自动化代码过渡到 REST API ， NetApp 提供了 API 映射文档。此参考包括 ONTAPI 调用列表以及每个调用的 REST API 等效项。此映射文档已进行更新，以包含新的 ONTAP 9.9.1 API 端点。请参见 https://library.netapp.com/ecm/ecm_download_file/ECMLP2876895["ONTAPI 到 REST API 映射"^] 有关详细信息 ...
API 端点，用于新的 ONTAP 9.9.1 核心功能:: REST API 中增加了对通过 ONTAPI 不可用的新 ONTAP 9.9.1 功能的支持。其中包括对嵌套 igroup 和 Google Cloud 密钥管理服务的支持。
改进了从 ONTAPI 过渡到 REST 的支持:: 现在，更多传统 ONTAPI 调用都具有相应的 REST API 等效项。其中包括本地 Unix 用户和组，无需客户端即可管理 NTFS 文件安全性， SAN 端口集以及卷空间属性。更新后的 ONTAPI to REST 映射文档也会包含这些更改。
增强的联机文档:: 现在， ONTAP 联机文档参考页面包含一些标签，用于指示引入每个 REST 端点或参数时的 ONTAP 版本，包括 ONTAP 9.1.1 中的新端点或参数。




== ONTAP 9.8

ONTAP 9.8 极大地扩展了 ONTAP REST API 的广度和深度。它包括多项新功能，可增强您自动部署和管理 ONTAP 存储系统的能力。此外，我们还改进了对帮助从原有 ONTAPI 过渡到 REST 的支持。

将 ONTAPI 映射到 ONTAP 9 REST API:: 为了帮助您更新 ONTAPI 自动化， NetApp 提供了一个需要一个或多个输入参数的 ONTAPI 调用列表，以及这些调用与等效的 ONTAP 9 REST API 调用的映射。请参见 https://library.netapp.com/ecm/ecm_download_file/ECMLP2874886["ONTAPI 到 REST API 映射"^] 有关详细信息 ...
API 端点，用于新的 ONTAP 9.8 核心功能:: REST API 中增加了对通过 ONTAPI 无法提供的新核心 ONTAP 9.8 功能的支持。其中包括对 ONTAP S3 分段和服务， SnapMirror 业务连续性和文件系统分析的 REST API 支持。
扩展了对增强安全性的支持:: 通过支持 Azure 密钥存储， Google Cloud 密钥管理服务， IPsec 和证书签名请求等多种服务和协议，安全性得到了增强。
增强功能可提高精简性:: ONTAP 9.8 可使用 REST API 提供更高效，更现代化的工作流。例如，现在可以对多种不同类型的固件进行一次性固件更新。
增强的联机文档:: 现在， ONTAP 联机文档页面包含一些标签，用于指示引入了每个 REST 端点或参数的 ONTAP 版本，包括 9.8 中的新版本。
改进了从 ONTAPI 过渡到 REST 的支持:: 现在，更多传统 ONTAPI 调用具有相应的 REST API 等效项。此外，我们还提供了一些文档来帮助您确定应使用哪个 REST 端点来取代现有的 ONTAPI 调用。
扩展了性能指标:: REST API 的性能指标已扩展，包括多个新的存储和网络对象。




== ONTAP 9.7

ONTAP 9.7 通过引入三个新的资源类别来扩展 ONTAP REST API 的功能范围，每个资源类别都有多个 REST 端点：

* NDMP
* 对象存储
* SnapLock


ONTAP 9.7 还会在多个现有资源类别中引入一个或多个新的 REST 端点：

* 集群
* NAS
* 网络
* NVMe
* SAN
* 安全性
* 存储
* 支持




== ONTAP 9.6

ONTAP 9.6 极大地扩展了最初在 ONTAP 9.4 中引入的 REST API 支持。ONTAP 9.6 REST API 支持大多数 ONTAP 配置和管理任务。

ONTAP 9.6 中的 REST API 包括以下关键方面以及更多方面：

* 集群设置
* 协议配置
* 配置
* 性能监控
* 数据保护
* 应用程序感知型数据管理

