---
sidebar: sidebar 
permalink: resources/cluster.html 
keywords: cluster resources 
summary: 您可以使用这些 API 调用来管理 ONTAP 集群和相关资源。 
---
= 集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理 ONTAP 集群和相关资源。

.容量池
通过容量池许可模式，您可以从共享池中为每个集群节点授予存储容量许可。此资源类型是 ONTAP 9.8 的新增功能。

.机箱
机箱是支持集群的硬件框架。此资源类型是在 ONTAP 9.6 中引入的。

.集群
ONTAP 集群包含一个或多个节点以及用于定义存储系统的相关配置设置。此资源类型是在 ONTAP 9.6 中引入的。

.计数器表
计数器管理器子系统会捕获有关ONTAP 的各种统计信息。您可以访问此信息以评估系统性能。此资源类型是在ONTAP 9.11中引入的。

.固件
您可以检索固件更新请求的历史记录。此资源类型是 ONTAP 9.8 的新增功能。

.作业
异步 REST API 请求使用由作业锁定的后台任务执行。此资源类型是在 ONTAP 9.6 中引入的。

.许可证实例
每个许可证都可以作为一个单独的软件包进行管理。此资源类型是在 ONTAP 9.6 中引入的。

.许可证管理器
您可以管理与 ONTAP 集群关联的每个许可证管理器实例相关的配置和其他信息。此资源类型是 ONTAP 9.8 的新增功能。

.licenses
通过这些许可证，您可以实施特定的 ONTAP 特性和功能。此资源类型是在 ONTAP 9.6 中引入的。

.调解器
您可以管理与 MetroCluster 关联的调解器，包括添加或删除调解器实例。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster
您可以创建和管理 MetroCluster 部署，包括执行切换或切回操作。此资源类型是ONTAP 9.8中的新增资源、更新为9.11。

.MetroCluster 诊断
您可以对 MetroCluster 部署执行诊断操作并检索结果。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster DR 组
您可以执行与 MetroCluster DR 组相关的操作。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster 互连
您可以检索 MetroCluster 互连状态。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster 节点
您可以检索 MetroCluster 部署中各个节点的状态。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster 操作
您可以检索 MetroCluster 配置的最近执行的操作列表。此资源类型是 ONTAP 9.8 的新增功能。

.MetroCluster SVM
您可以检索有关MetroCluster 配置中所有SVM对的信息。此资源类型是在ONTAP 9.11.1中引入的。

.节点
ONTAP 集群由一个或多个节点组成。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

.NTP keys
可以将网络时间协议（ NTP ）配置为在 ONTAP 和可信外部 NTP 时间服务器之间使用共享私钥。此资源类型是在 ONTAP 9.7 中引入的。

.NTP 服务器
您可以使用这些 API 调用来配置 ONTAP 网络时间协议设置，包括外部 NTP 服务器和密钥。此资源类型是在 ONTAP 9.7 中引入的。

.peers
对等对象表示端点并支持集群对等关系。此资源类型是在 ONTAP 9.6 中引入的。

.性能计数器
先前版本的ONTAP 保留了有关系统运行特征的统计信息。在9.11.1版中、此信息已得到增强、现在可通过REST API获得。此功能使ONTAP REST API更接近与Data ONTAP API (ONTAPI或ZAPI)的奇偶校验。此资源类型是在ONTAP 9.11中引入的。

.资源标记
您可以使用标记对REST API资源进行分组。您可以执行此操作来关联特定项目或组织组中的相关资源。使用标记有助于更有效地组织和跟踪资源。此资源类型是在ONTAP 9.13中引入的。

.Schedules
计划可用于自动执行任务。此资源类型是在 ONTAP 9.6 中引入的。

.传感器
您可以使用这些端点检索有关所有平台环境传感器的详细信息。此资源类型是在ONTAP 9.11中引入的。

.软件
ONTAP 集群包括集群软件配置文件，软件包收集和软件历史记录收集。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

.Web
您可以使用这些端点更新 Web 服务配置并检索当前配置。此资源类型是在 ONTAP 9.10 中引入的。
