---
sidebar: sidebar 
permalink: resources/nas.html 
keywords: nas resources 
summary: 您可以使用这些 API 调用来管理集群和 SVM 的 CIFS 和 NFS 设置。 
---
= NAS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理集群和 SVM 的 CIFS 和 NFS 设置。

您可以管理为ONTAP 集群定义的Active Directory帐户。其中包括创建新帐户以及显示、更新和删除帐户。ONTAP 9.12增加了此支持。

可以为 SVM 记录某些 CIFS 和 NFS 事件，这有助于提高安全性。此资源类型是在 ONTAP 9.6 中引入的。

您可以将 NAS 审核事件重定向到特定 SVM 。此资源类型是 ONTAP 9.8 的新增功能。

您可以检索已建立的CIFS连接的列表。此资源类型是在ONTAP 9.11.1中引入的。

在集群和 SVM 级别添加了对 CIFS 域的支持，其中包含多种类型的端点。您可以检索域配置以及创建和删除首选域控制器。此资源类型是 ONTAP 9.10 中的新增资源。

添加了端点、以支持创建和管理CIFS组策略。配置信息可通过应用于所有或特定SVM的组策略对象进行访问和管理。ONTAP 9.12增加了此支持。

可以在 CIFS 服务器上为 SMB 用户创建主目录，而无需为每个用户创建单独的 SMB 共享。主目录搜索路径是从 SVM 根目录开始的一组绝对路径。此资源类型是在 ONTAP 9.6 中引入的。

在确定共享，文件和目录访问权限时， CIFS 服务器可以使用本地组进行授权。此资源类型是在 ONTAP 9.9 中引入的，并在 ONTAP 9.10 中进行了显著扩展。

您可以显示有关集群的NetBIOS连接的信息。详细信息包括IP地址和已注册的NetBIOS名称。此信息可帮助您解决名称解析问题。此资源类型是在ONTAP 9.11.1中引入的。

CIFS 服务器的核心配置。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。

您可以根据多个筛选选项检索CIFS会话的打开文件列表。此资源类型是在ONTAP 9.11.1中引入的。

您可以使用此 API 检索有关 CIFS 会话的详细信息。此资源类型是在 ONTAP 9.8 REST API 中引入的，并在 ONTAP 9.9 中进行了增强。

Microsoft远程卷影复制服务是现有Microsoft VSS功能的扩展。它扩展了VSS功能、支持SMB共享的卷影复制。此功能现在可通过ONTAP REST API来使用。此资源类型是在ONTAP 9.11.1中引入的。

在 CIFS 服务器上定义的 SMB 共享。此资源类型是在 ONTAP 9.6 中引入的。

访问控制列表（ ACL ）用于控制对 CIFS 共享上的文件夹和文件的访问。此资源类型是在 ONTAP 9.6 中引入的。

CIFS 和 UNIX 客户端均可访问同一数据存储库。当 UNIX 客户端创建符号链接时，这些映射会引用其他文件或文件夹来支持 CIFS 客户端。此资源类型是在 ONTAP 9.6 中引入的。

您可以使用新的REST API端点批量导入CIFS本地用户、组和组成员资格信息、并监控请求的状态。此资源类型是在ONTAP 9.11.1中引入的。

您可以使用这些 API 调用来跟踪对特定文件的访问。此资源类型是 ONTAP 9.8 的新增功能。

您可以使用这些 API 调用来显示为 Windows 或 Unix 用户授予的特定文件或文件夹的有效权限。您还可以管理 NTFS 文件安全性和审核策略。此资源类型是在 ONTAP 9.8 REST API 中引入的，并在 ONTAP 9.9 中得到了显著增强。

FPolicy 是一个文件访问通知框架，用于监控和管理 SVM 上的文件访问事件。此资源类型是在 ONTAP 9.6 中引入的。

通过这些端点，您可以显示和更新外部 FPolicy 服务器的连接状态信息。此资源类型是在 ONTAP 9.10 中引入的。

通过 FPolicy 引擎，您可以确定接收文件访问通知的外部服务器。此资源类型是在 ONTAP 9.6 中引入的。

用于确定如何监控文件访问以及生成哪些事件的配置。此资源类型是在 ONTAP 9.6 中引入的。

FPolicy 框架要素的容器，包括 FPolicy 引擎和事件。此资源类型是在 ONTAP 9.6 中引入的。

锁定是一种同步机制，用于对同时访问多个客户端同时访问同一文件的文件实施限制。您可以使用这些端点检索和删除锁定。此资源类型是在 ONTAP 9.10 中引入的。

已连接客户端的NFS映射信息可通过新端点访问。您可以检索有关节点、SVM和IP地址的详细信息。此资源类型是在ONTAP 9.11.1中引入的。

您可以显示已连接客户端的列表及其连接详细信息。此资源类型是在 ONTAP 9.7 中引入的。

包含用于描述 NFS 导出的规则的策略。此资源类型是在 ONTAP 9.6 中引入的。

Kerberos 接口的配置设置。此资源类型是在 ONTAP 9.6 中引入的。

Kerberos 域的配置设置。此资源类型是在 ONTAP 9.6 中引入的。

NFS 服务器的核心配置。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。

对 S3 事件的审核是一项安全改进，可用于跟踪和记录某些 S3 事件。可以为每个存储分段的每个 SVM 设置 S3 审核事件选择器。此资源类型是在 ONTAP 9.10 中引入的。

一种安全功能，用于保护您的数据免受病毒和其他恶意代码的影响。此资源类型是在 ONTAP 9.6 中引入的。

Vscan 策略允许在客户端访问时主动扫描文件对象。此资源类型是在 ONTAP 9.6 中引入的。

Vscan 策略允许根据需要或设置的计划立即扫描文件对象。此资源类型是在 ONTAP 9.6 中引入的。

一组属性，用于管理 ONTAP 与外部病毒扫描服务器之间的连接。此资源类型是在 ONTAP 9.6 中引入的。

外部病毒扫描服务器的状态。此资源类型是在 ONTAP 9.6 中引入的。
