---
sidebar: sidebar 
permalink: resources/networking.html 
keywords: networking resources 
summary: 您可以使用这些 API 调用来管理与集群一起使用的物理和逻辑网络资源。 
---
= 网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理与集群一起使用的物理和逻辑网络资源。

您可以创建和管理边界网关协议对等组。此资源类型是在 ONTAP 9.7 中引入的。

以太网广播域是一组物理端口，这些端口似乎属于同一物理网络。当从域中的一个端口广播时，所有端口都会收到一个数据包。每个广播域都属于一个 IP 空间。此资源类型是在 ONTAP 9.6 中引入的。

以太网端口是物理或虚拟网络端点。这些端口可以组合成链路聚合组（ Link Aggregate Group ， LAG ），也可以使用虚拟 LAN （ Virtual LAN ， VLAN ）进行分隔。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

您可以检索以太网交换机的端口信息。此资源类型是 ONTAP 9.8 的新增功能。

您可以检索或修改用于 ONTAP 集群或存储网络的以太网交换机的配置。此资源类型是ONTAP 9.8中的新增资源、更新为9.11。

您可以使用光纤通道(FC)光纤REST API端点检索有关FC网络的信息。其中包括ONTAP 集群与FC网络结构之间的连接、构成网络结构的交换机以及活动区域集的分区。此资源类型是在ONTAP 9.11中引入的。

光纤通道接口是与 SVM 关联的逻辑端点。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

光纤通道端口是 ONTAP 节点上用于连接到光纤通道网络的物理适配器。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

您可以为 SVM 或集群 IP 空间配置 HTTP 代理。此资源类型是在 ONTAP 9.7 中引入的。

逻辑接口（ LIF ）是一个具有其他配置属性的 IP 地址。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

路由表是用于将流量转发到其目标的一组 IP 路由。此资源类型是在 ONTAP 9.6 中引入的。

IP 服务策略用于定义特定 LIF 上可用的服务。可以在 SVM 或 IP 空间的上下文中配置服务策略。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

ONTAP 网络连接功能已进行扩展、可支持IP子网。通过REST API、您可以配置和管理ONTAP 集群中的IP子网。此资源类型是在ONTAP 9.11中引入的。

IP 空间会创建一个网络空间来支持一个或多个 SVM 。IP 空间可以彼此隔离，从而提供安全和隐私保护。此资源类型是在 ONTAP 9.6 中引入的。
