---
sidebar: sidebar 
permalink: resources/networking.html 
keywords:  
summary:  
---
= 网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理与集群一起使用的物理和逻辑网络资源。



==== 以太网广播域

以太网广播域是一组物理端口，这些端口似乎属于同一物理网络。当从域中的一个端口广播时，所有端口都会收到一个数据包。每个广播域都属于一个 IP 空间。此资源类型是在 ONTAP 9.6 中引入的。



==== 以太网端口

以太网端口是物理或虚拟网络端点。这些端口可以组合成链路聚合组（ Link Aggregate Group ， LAG ），也可以使用虚拟 LAN （ Virtual LAN ， VLAN ）进行分隔。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== 以太网交换机端口

您可以检索以太网交换机的端口信息。此资源类型是 ONTAP 9.8 的新增功能。



==== 以太网交换机

您可以检索或修改用于 ONTAP 集群或存储网络的以太网交换机的配置。此资源类型是 ONTAP 9.8 的新增功能。



==== 光纤通道接口

光纤通道接口是与 SVM 关联的逻辑端点。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== 光纤通道端口

光纤通道端口是 ONTAP 节点上用于连接到光纤通道网络的物理适配器。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== HTTP 代理

您可以为 SVM 或集群 IP 空间配置 HTTP 代理。此资源类型是在 ONTAP 9.7 中引入的。



==== BGP 对等组

您可以创建和管理边界网关协议对等组。此资源类型是在 ONTAP 9.7 中引入的。



==== IP 接口

逻辑接口（ LIF ）是一个具有其他配置属性的 IP 地址。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== IP 路由

路由表是用于将流量转发到其目标的一组 IP 路由。此资源类型是在 ONTAP 9.6 中引入的。



==== IP 服务策略

IP 服务策略用于定义特定 LIF 上可用的服务。可以在 SVM 或 IP 空间的上下文中配置服务策略。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。



==== IP 空间

IP 空间会创建一个网络空间来支持一个或多个 SVM 。IP 空间可以彼此隔离，从而提供安全和隐私保护。此资源类型是在 ONTAP 9.6 中引入的。
