---
sidebar: sidebar 
permalink: resources/san.html 
keywords: san resources 
summary: 您可以使用这些API调用来管理SAN资源。 
---
= ONTAP REST API中的SAN资源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理存储区域网络（ Storage Area Networking ， SAN ）资源。

.光纤通道登录
光纤通道登录表示已登录到 ONTAP 的光纤通道启动程序所形成的连接。此资源类型是在 ONTAP 9.6 中引入的。

.光纤通道协议服务
光纤通道协议（ FCP ）服务定义 SVM 的光纤通道目标的属性。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。ONTAP 9.14增加了对检索性能指标数据的支持。

.光纤通道 WWPN 别名
全球通用端口名称（ WWPN ）是一个 64 位值，用于唯一标识光纤通道端口。此资源类型是在 ONTAP 9.6 中引入的。

.igroup
启动程序组（ igroup ）是一组光纤通道 WWPN （全球通用端口名称）， iSCSI IQN （限定名称）和 iSCSI EUI （扩展唯一标识符），用于标识主机启动程序。此资源类型最初是在 ONTAP 9.6 中推出的。

嵌套 igroup 是 ONTAP 9.9 的一项新功能，也已向 REST API 添加了支持。此 REST 资源类型是在 ONTAP 9.9 中引入的。

.启动程序
启动程序是用于标识主机端点的光纤通道(FC)全球通用端口名称(WWPN)、iSCSI限定名称(IQN)或iSCSI EUI (扩展唯一标识符)。您可以检索集群或特定SVM的启动程序。此资源类型是在ONTAP 9.14中引入的。

.iSCSI 凭据
iSCSI 凭据对象包含启动程序和 ONTAP 使用的身份验证凭据。此资源类型是在 ONTAP 9.6 中引入的。

.iSCSI 服务
iSCSI 服务定义 SVM 的 iSCSI 目标的属性。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。ONTAP 9.14增加了对检索性能指标数据的支持。

.iSCSI 会话
iSCSI 会话是指将 iSCSI 启动程序与 iSCSI 目标链接在一起的一个或多个 TCP 连接。此资源类型是在 ONTAP 9.6 中引入的。

.LUN 属性
LUN 属性是由调用方定义的名称 / 值对，可以选择随 LUN 一起存储。属性可用于保存少量应用程序专用元数据，不会被 ONTAP 解释。通过这些端点，您可以创建，更新，删除和发现 LUN 的属性。此资源类型是在 ONTAP 9.10 中引入的。

.LUN 映射
LUN 映射是指 LUN 与启动程序组之间的关联。此资源类型是在 ONTAP 9.6 中引入的。

.LUN 映射报告节点
报告节点是指在 ONTAP 的选择性 LUN 映射（ SLM ）功能中使用 SAN 协议公布映射 LUN 的网络路径的集群节点。通过这些新端点，您可以添加，删除和发现 LUN 映射的报告节点。此资源类型是在 ONTAP 9.10 中引入的。

.LUN
LUN 是存储区域网络（ SAN ）中存储的逻辑表示形式。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。ONTAP 9.14增加了对检索性能指标数据的支持。

.端口集
端口集是与 _portset_ Storage VM 关联的一组光纤通道或 iSCSI 网络接口。虽然先前版本的 ONTAP 中已存在此功能，但现在已向 REST API 添加了支持。此 REST 资源类型是在 ONTAP 9.9 中引入的。

.VVol 绑定
VMware 虚拟卷（ VVol ）绑定是指类为 `protocol_endpoint` 的 LUN 与类为 `vvol` 的 LUN 之间的关联。您可以使用 VVol 绑定 REST API 创建，删除和发现 VVol 绑定。此资源类型是在 ONTAP 9.10 中引入的。
