---
sidebar: sidebar 
permalink: resources/security.html 
keywords: rest, rest api, security, security resources 
summary: 您可以使用这些 API 调用来管理集群和 SVM 的安全设置。 
---
= ONTAP REST API中的安全资源
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理集群和 SVM 的安全设置。

.—帐户
集群和 SVM 有一组用户帐户。此资源类型是在 ONTAP 9.6 中引入的。

.帐户名称
范围内的用户帐户的配置。此资源类型是在 ONTAP 9.6 中引入的。

.Active Directory 代理
您可以在 Active Directory 服务器上管理 SVM 帐户信息。此资源类型是在 ONTAP 9.7 中引入的。

.反勒索软件
ONTAP 会检测可能包含勒索软件威胁的文件。端点有多种类别。您可以检索这些可疑文件的列表并将其从卷中删除。此资源类型是在ONTAP 9.10.1中引入的。ONTAP 9 .16增加了对显示版本和更新反勒索软件包的支持。

.反勒索软件熵统计
针对自主勒索软件防护 (ARP) 功能的运行，提供了详细的熵统计信息。此资源类型已在ONTAP 9.17.1 中添加。

.Audit
用于确定审核日志文件中记录的内容的设置。此资源类型是在 ONTAP 9.6 中引入的。

.审核目标
这些设置控制将审核日志信息转发到远程系统或 Splunk 服务器的方式。此资源类型是在 ONTAP 9.6 中引入的。

.审核消息
您可以检索审核日志消息。此资源类型是在 ONTAP 9.6 中引入的。

.AWS KMS
Amazon Web Services包括一项密钥管理服务、可为密钥和其他机密提供安全存储。您可以通过REST API访问此服务、以使ONTAP 能够将其加密密钥安全地存储在云中。此外、您还可以创建和列出用于NetApp存储加密的身份验证密钥。此支持是ONTAP 9.12的新增功能。

.Azure 密钥存储
通过这组 API 调用，您可以使用 Azure 密钥存储来存储 ONTAP 加密密钥。此资源类型是 ONTAP 9.8 的新增功能。

.巴比肯 KMS
已添加对 OpenStack Barbican 密钥管理器的支持，以维护NetApp卷加密 (NVE) 的密钥。此资源类型已在ONTAP 9.17.1 中添加。

.证书
API 调用可用于安装，显示和删除 ONTAP 使用的证书。此资源类型是在 ONTAP 9.7 中引入的。

.Cisco Duo
Duo为SSH登录提供双重身份验证。您可以将Duo配置为在ONTAP集群或SVM级别运行。此资源类型是在ONTAP 9.14中引入的。

.集群安全性
您可以检索集群范围安全性的详细信息并更新某些参数。此资源类型是在 ONTAP 9.7 中引入的，并在 ONTAP 9.8 中进行了更新。

.外部角色
外部角色在OAuth2.0标识提供程序中定义。您可以创建和管理这些外部角色与ONTAP角色之间的映射关系。此资源类型是在ONTAP 9.16中引入的。

.GCP KMS
通过这组 API 调用，您可以使用 Google 云平台密钥管理服务来存储和管理 ONTAP 加密密钥。此资源类型最初是在 ONTAP 9.8 REST API 中引入的。但是，此功能已经过重新设计，因此在 ONTAP 9.9 中被视为新增资源类型。

.组
您可以管理组配置、包括使用UID表示的组。此资源类型是在ONTAP 9.16中引入的。

.组角色映射
您可以创建和管理组和角色之间的映射关系。此资源类型是在ONTAP 9.16中引入的。

.IPsec
Internet 协议安全性（ Internet Protocol Security ， IPsec ）是一套协议，可通过底层 IP 网络在两个端点之间提供安全性。此资源类型是 ONTAP 9.8 的新增功能。

.IPsec CA 证书
您可以添加，删除和检索 IPsec CA 证书。此资源类型是 ONTAP 9.10 中的新增资源。

.IPsec 策略
您可以使用这组 API 调用来管理对 IPsec 部署有效的策略。此资源类型是 ONTAP 9.8 的新增功能。

.IPsec 安全关联
您可以使用这组 API 调用来管理对 IPsec 部署有效的安全关联。此资源类型是 ONTAP 9.8 的新增功能。

.即时 (JIT) 权限提升
(JIT) 权限提升是对基于角色的访问控制 (RBAC) 的增强。集群管理员可以请求临时提升到现有角色。此资源类型已在ONTAP 9.17.1 中添加。

.密钥管理器配置
通过这些端点，您可以检索和更新密钥管理器的配置。此资源类型是 ONTAP 9.10 中的新增资源。

.密钥管理器
密钥管理器允许 ONTAP 中的客户端模块安全地存储密钥。此资源类型是在 ONTAP 9.6 中引入的，并针对 ONTAP 9.7 进行了更新。另外、还对ONTAP 9.12进行了更新、以支持身份验证密钥。ONTAP 9.13增加了还原功能。

.密钥存储
密钥存储用于描述密钥管理器的类型。此资源类型是 ONTAP 9.10 中的新增资源。ONTAP 9.14增加了支持增强控制的其他端点。

.LDAP 身份验证
这些 API 调用用于检索和管理集群 LDAP 服务器配置。此资源类型是在 ONTAP 9.6 中引入的。

.登录消息
用于显示和管理 ONTAP 使用的登录消息。此资源类型是在 ONTAP 9.6 中引入的。

.多个管理员验证
多管理员验证功能提供了一个灵活的授权框架、用于保护对ONTAP 命令或操作的访问。在以下方面、有17个新端点支持定义、请求和批准访问：

* rules
* 请求
* 批准组


为多个管理员提供批准访问的选项可提高ONTAP 和IT环境的安全性。这些资源类型是在ONTAP 9.11中引入的。

.NIS 身份验证
这些设置用于检索和管理集群 NIS 服务器配置。此资源类型是在 ONTAP 9.6 中引入的。

.OAuth2.0
开放式授权(OAuth2.0)是一种基于令牌的框架、可用于限制对ONTAP存储资源的访问。您可以将其用于通过REST API访问ONTAP的客户端。此资源类型是在ONTAP 9.14中引入的。通过支持具有标准OAuth2.0声明的Microsoft Entra ID授权服务器(以前称为Azure AD)，它在ONTAP 9™16中得到了增强。此外、还可以通过新的组和角色映射功能支持基于UUID样式值的Entra ID标准组声明。还引入了一项新的外部角色映射功能。另请参见*外部角色*、*组*和*组角色映射*。

.密码身份验证
这包括用于更改用户帐户密码的 API 调用。此资源类型是在 ONTAP 9.6 中引入的。

.角色实例的特权
管理特定角色的特权。此资源类型是在 ONTAP 9.6 中引入的。

.公有密钥身份验证
您可以使用这些 API 调用为用户帐户配置公有密钥。此资源类型是在 ONTAP 9.7 中引入的。

.角色
这些角色提供了一种向用户帐户分配权限的方法。此资源类型是在 ONTAP 9.6 中引入的。

.角色实例
角色的特定实例。此资源类型是在 ONTAP 9.6 中引入的。

.SAML 服务提供程序
您可以显示和管理 SAML 服务提供程序的配置。此资源类型是在 ONTAP 9.6 中引入的。

.SAML 服务提供商默认元数据
您可以管理集群的 SAML 默认元数据配置。此资源类型是在ONTAP 9.17.1 中添加的。

.SSH
通过这些调用，您可以设置 SSH 配置。此资源类型是在 ONTAP 9.7 中引入的。

.SSH SVMs
通过这些端点，您可以检索所有 SVM 的 SSH 安全配置。此资源类型是在 ONTAP 9.10 中引入的。

.TOTPS
您可以使用REST API为使用SSH登录和访问ONTAP 的帐户配置基于时间的一次性密码(TOTP)配置文件。此资源类型是在ONTAP 9.13中引入的。

.Web身份验证
Web身份验证(WebAuthn)是一种Web标准、用于根据公共密钥加密对用户进行安全身份验证。借助ONTAP、它支持通过System Manager和ONTAP REST API管理可抵御网络钓鱼的MSA。此功能是在ONTAP 9 16中添加的。
