---
sidebar: sidebar 
permalink: resources/storage.html 
keywords: storage resources 
summary: 您可以使用这些 API 调用来管理物理和逻辑存储。 
---
= 存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理物理和逻辑存储。

.聚合指标
您可以检索特定聚合的历史指标数据。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。

.聚合丛
聚合中 WAFL 存储的物理副本。此资源类型是在 ONTAP 9.6 中引入的。

.聚合
聚合包含一个或多个 RAID 组。此资源类型是在 ONTAP 9.6 中引入的。

.网桥
您可以检索集群中的网桥。此资源类型是在 ONTAP 9.9 中引入的。

.Disks
集群中的物理磁盘。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 和 9.8 中进行了更新。

.文件克隆
您可以使用这些端点创建文件克隆，检索拆分状态以及管理拆分负载。文件克隆端点资源最初是在 ONTAP 9.6 中推出的，并在 ONTAP 9.8 中进行了扩展。它们在 ONTAP 9.10 中再次显著扩展。

.文件移动
您可以使用这些REST API端点在两个FlexVol 卷之间或FlexGroup 卷内移动文件。接受请求后、您可以监控进度和状态。此资源类型是在ONTAP 9.11.1中引入的。

.FlexCache
此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.8 中进行了更新。

.FlexCache 起源
FlexCache 是原始卷的永久性缓存。此资源类型最初是在 ONTAP 9.6 中推出的。ONTAP 9.9 REST API 增强了支持，支持通过 HTTP 修补方法进行修改。

.受监控的文件
您可以指定特定文件以进行额外监控。此资源类型是 ONTAP 9.8 的新增功能。

.池
您可以创建共享存储池并检索集群中的存储池。此资源类型是在ONTAP 9.11.1中引入的。

.端口
集群的存储端口。此资源类型是在ONTAP 9.6中推出的、并在ONTAP 9.11.1中进行了增强。

.QoS 策略
服务质量策略配置。此资源类型是在 ONTAP 9.6 中引入的。

.QoS选项
通过引入端点、您可以检索和设置集群的QoS选项。例如、您可以为后台任务预留一定百分比的可用系统处理资源。此资源类型是在ONTAP 9.14中引入的。

.QoS 工作负载
QoS 工作负载表示通过 QoS 跟踪的存储对象。您可以检索 QoS 工作流。此资源类型是在 ONTAP 9.10 中引入的。

.qtree
您可以使用这些 API 调用来管理 qtree ， qtree 是一种按逻辑划分的文件系统。此资源类型是在ONTAP 9.6中引入的。qtree扩展性能监控功能是在ONTAP 9 16.1中添加的。

.配额报告
报告配额，这是一种用于限制或跟踪文件或空间使用量的技术。此资源类型是在 ONTAP 9.6 中引入的。

.配额规则
用于强制实施配额的规则。此资源类型是在 ONTAP 9.6 中引入的，并在 ONTAP 9.7 中进行了更新。

.磁盘架
集群中的磁盘架。此资源类型是在 ONTAP 9.6 中引入的。

.Snapshot 策略
快照是根据策略创建的。此资源类型是在 ONTAP 9.6 中引入的。

.Snapshot 计划
您可以控制快照计划。此资源类型在 ONTAP 9.8 中进行了新的重新设计。

.交换机
您可以检索集群中的交换机。此资源类型是在 ONTAP 9.9 中引入的。

.磁带设备
您可以检索集群中的磁带设备。此资源类型是在 ONTAP 9.9 中引入的。

.首要指标
您可以通过排名靠前的指标端点来确定按特定指标筛选的卷的活动。可以根据客户端，目录，文件和用户进行筛选。此资源类型是在 ONTAP 9.10 中引入的。

.卷效率策略
您可以使用这些 API 调用来配置应用于整个卷的效率。此资源类型是 ONTAP 9.8 的新增功能。

.Volumes
逻辑容器用于向客户端提供数据。此资源类型最初是在 ONTAP 9.6 REST API 中引入的。在 ONTAP 9.9 中， API 中使用的许多参数值都得到了显著扩展，包括用于空间管理的参数值。

.卷文件
您可以检索卷上特定目录的文件和目录列表。此资源类型是在 ONTAP 9.7 中引入的，并在 ONTAP 9.8 中进行了更新。

.卷快照
卷的快照。此资源类型是在 ONTAP 9.6 中引入的。
