---
sidebar: sidebar 
permalink: resources/support.html 
keywords: support resources 
summary: 您可以使用这些 API 调用来管理用于支持集群的 ONTAP 功能。 
---
= 支持
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用这些 API 调用来管理用于支持集群的 ONTAP 功能。

独立应用程序可以通过发出POST请求在ONTAP 系统上记录EMS事件以及可选生成的AutoSupport 软件包。此资源类型是在ONTAP 9.11.1中引入的

自动更新功能可通过下载并应用最新的软件更新来使 ONTAP 系统保持最新。支持此功能的端点类别有多种，包括状态，配置和更新。这些资源类型是在 ONTAP 9.10 中引入的。

AutoSupport 会收集配置和状态详细信息以及错误，并向 NetApp 报告这些信息。此资源类型是在 ONTAP 9.6 中引入的。

每个节点都会维护可生成和检索的 AutoSupport 消息。此资源类型是在 ONTAP 9.6 中引入的。

您可以使用这些 API 检索和更新当前备份设置。此资源类型是在 ONTAP 9.6 中引入的。

您可以创建，检索和删除配置备份文件。此资源类型是在 ONTAP 9.7 中引入的。

您可以使用这些端点检索和管理集群或节点生成的内存核心转储。此资源类型是在 ONTAP 9.10 中引入的。

事件管理系统（ EMS ）收集事件并向一个或多个目标发送通知。此资源类型是在 ONTAP 9.6 中引入的。

EMS 目标可确定通知的发送方式和发送位置。此资源类型是在 ONTAP 9.6 中引入的。

EMS 目标实例按类型和位置定义。此资源类型是在 ONTAP 9.6 中引入的。

这是集群的实时系统事件集合。此资源类型是在 ONTAP 9.6 中引入的。

EMS 筛选器可共同识别需要额外处理的事件。此资源类型是在 ONTAP 9.6 中引入的。

EMS 筛选器实例是应用于事件的规则的集合。此资源类型是在 ONTAP 9.6 中引入的。

可用于访问 EMS 事件目录。此资源类型是在 ONTAP 9.6 中引入的。

可以为 EMS 筛选器的特定实例管理规则列表。此资源类型是在 ONTAP 9.6 中引入的。

EMS 筛选器的特定实例的单个规则。此资源类型是在 ONTAP 9.6 中引入的。

您可以为集群启用和禁用 SNMP 和陷阱操作。此资源类型是在 ONTAP 9.7 中引入的。

SNMP 陷阱主机是一个配置为从 ONTAP 接收 SNMP 陷阱的系统。您可以检索和定义主机。此资源类型是在 ONTAP 9.7 中引入的。

您可以管理特定的 SNMP 陷阱主机。此资源类型是在 ONTAP 9.7 中引入的。

您可以定义和管理 SNMP 用户。此资源类型是在 ONTAP 9.7 中引入的。

您可以管理引擎 ID 与管理 SVM 或数据 SVM 关联的特定 SNMP 用户。此资源类型是在 ONTAP 9.7 中引入的。
