---
sidebar: sidebar 
permalink: python/learn-about-pcl.html 
keywords: learn about python client library, learn about pcl, pcl overview, pcl 
summary: NetApp ONTAP Python客户端库是一个软件包、您可以安装它并使用它来快速编写访问ONTAP REST API的脚本。在使用本地运行时环境之前、您需要对其进行准备。 
---
= 了解ONTAP Python客户端库
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP Python客户端库是一个软件包、您可以安装它并使用它来快速编写访问ONTAP REST API的脚本。在使用本地运行时环境之前、您需要对其进行准备。


NOTE: 您还应查看中提供的资源link:../additional/learn_more.html["详细了解ONTAP REST API"]。

.优势和功能
您可以使用Python客户端库快速开发强大的代码、以自动管理ONTAP部署。它提供多种底层服务、包括：

* 连接管理
* 异步处理
* 异常处理
* 统一错误消息


.软件包名称和版本
Python 客户端库软件包的名称是 * 。 netapp-ontap* 。与软件包关联的版本是生成库时使用的ONTAP主要版本号和次要版本号的组合、以及ONTAP发行版中客户端库的次要版本。例如、有效版本号包括9.5.1、9.7.2和9.7.2。

.安装
必须使用*pip*实用程序ONTAP从NetApp软件包索引(PyPI)站点安装Pypon_Python软件包。

.ONTAP版本的软件包和文档
从9.6开始的每个ONTAP版本都有一个PyPI软件包和相关文档。有关详细信息、请参见 link:../python/packages.html["软件包和文档"] 。每个软件包都包含安装要求、并指定以下各项的不同版本：

* Python
* 请求
* Requests-toolbelt
* 棉花糖


.代码示例
NetApp维护着一个GitHub存储库、其中包含代码示例和其他有用信息。您可以导航到 _examples_ 文件夹以使用 Python 客户端库访问示例。有关详细信息、请参见GitHub上的以下位置：

* https://github.com/NetApp/ontap-rest-python["ONTAP REST Python GitHub 存储库"^]
* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["ONTAP REST Python客户端库示例"^]

