---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: 您可以通过多种不同方式访问 ONTAP REST API 。 
---
= 如何访问ONTAP REST API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以通过多种不同方式访问 ONTAP REST API 。



== 网络注意事项

您可以使用多种类型的接口之一连接到ONTAP REST API。您选择的 LIF 需要配置为支持 HTTPS 管理协议。此外，您网络中的防火墙配置必须允许 HTTPS 流量。支持以下接口：

* 集群管理 LIF
* 节点管理 LIF
* SVM 管理 LIF


虽然您可以使用这些 LIF 中的任何一个，但推荐的最佳实践是使用集群管理 LIF。这样一来，集群就可以作为一个单一的逻辑单元进行寻址，从而提供最高级别的弹性和负载均衡。集群 LIF 可以根据需要重新定位到集群中，以处理计划内的升级、仲裁事件和其他连接问题。如果配置了多个集群管理 LIF，它们在访问 REST API 方面都是等效的。SVM 管理 LIF 也进行了负载均衡，但发送到节点级别 LIF 的请求会在本地处理。



== ONTAP API 联机文档页面

使用 Web 浏览器时， ONTAP API 联机文档页面提供了一个访问点。除了提供直接执行单个 API 调用的方法之外，此页面还包括 API 的详细问题描述，包括每个调用的输入参数和其他选项。API 调用按功能类别进行组织。请参见 link:../resources/overview_categories.html["REST 资源摘要"] 有关详细信息 ...

用于访问最新版本 API 的文档页面的 URL 格式为：

`\https://<cluster_mgmt_ip_address>/docs/api`



== 自定义软件和工具

您可以使用多种不同的编程语言和工具访问 ONTAP API 。常见选项包括 Python ， Java ， Curl 和 PowerShell 。使用 API 的程序，脚本或工具充当 REST Web 服务客户端。使用编程语言可以加深对 API 的了解，并提供自动化 ONTAP 管理的机会。

用于直接访问最新版本 API 的基本 URL 格式为：

`\https://<cluster_mgmt_ip_address>/api`

要访问支持多个版本的特定 API 版本， URL 的格式为：

`\https://<cluster_mgmt_ip_address>/api/v1`
