---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog 
summary: 您可以通过多种方法自动部署和管理ONTAP存储系统。 
---
= 了解 ONTAP 自动化选项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以通过多种方法自动部署和管理ONTAP存储系统。



== ONTAP REST API

从ONTAP 9.6 开始， ONTAP包含一个强大的 REST API，为自动部署和管理存储系统奠定了基础。从那时起，REST API 不断扩展和成熟。现在，它在自动化ONTAP部署管理时提供了首选和战略性的选择。

.本机访问REST API
您可以使用支持 REST 客户端的任何编程语言直接访问 ONTAP REST API 。常见语言选项包括 Python ， PowerShell 和 Java 。

.正在迁移旧版ONTAPI代码以使用REST
ONTAPI API（Zephyr API 或 ZAPI）是NetApp ONTAP软件中包含的原始专有调用集，用于支持数据存储管理和管理任务的自动化。 API 是link:../sw-tools/learn-about-nmsdk.html["NetApp 易管理性 SDK"]。如果您现有的代码使用 ONTAPI API，则应计划迁移到ONTAP REST API，以利用 REST API 提供的扩展功能集。 NetApp提供将您的代码转换为使用较新的ONTAP REST API 的支持。看link:../migrate/migration-considerations.html["从ONTAPI迁移到REST API"]了解更多信息。



== 客户端软件工具包

NetApp提供的客户端工具包可对ONTAP REST API进行抽象化、并使创建自动化代码变得更加轻松。您应选择一种适合您的开发语言和环境的解决方案。

.Python 客户端库
Python 客户端库是一个软件包，您可以在编写脚本以访问 ONTAP REST API 时使用。它支持多种底层服务，包括连接管理，异步请求处理和异常处理。通过使用 Python 客户端库，您可以快速开发强大的代码来支持您的 ONTAP 自动化目标。有关详细信息、请参见 link:../python/learn-about-pcl.html["Python 客户端库"] 。

.PowerShell工具包
您可以使用NetApp.ONTAP PowerShell工具包从Windows主机自动管理ONTAP集群。有关详细信息、请参见 link:../pstk/learn-about-pstk.html["了解NetApp PowerShell工具包"] 。



== 自动化框架

您可以使用多个框架之一来创建和部署自动化代码。

.Ansible
Ansible 是一款开源软件工具，支持配置，配置管理和应用程序部署。自 RedHat 发布并随后获得该软件以来，该软件的受欢迎程度不断提高。NetApp 提供了 Ansible 认证模块，客户可以使用这些模块自动管理 ONTAP 存储系统。请参见 link:../additional/learn_more.html["了解更多信息。"] 和 https://www.netapp.com/devops-solutions/ansible/["NetApp Ansible DevOps 解决方案"^] 适用于追加信息 。

.BlueXP自动化目录
NetApp https://console.bluexp.netapp.com/automationCatalog/["BlueXP自动化目录"^] 可通过BlueXP Web用户界面访问。通过该目录、您可以访问打包的解决方案、这些解决方案有助于自动部署ONTAP并将其与其他产品集成。请参见 https://docs.netapp.com/us-en/netapp-automation/["NetApp自动化"^] 有关文档和详细信息、请参见。
