---
sidebar: sidebar 
permalink: rest/object_references_and_access.html 
keywords: objects, access paths, uuid, uuidv4, collections, object collection 
summary: 通过 ONTAP REST API 公开的资源实例或对象可以通过多种不同的方式进行引用和访问。 
---
= ONTAP REST API对象引用和访问
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
通过 ONTAP REST API 公开的资源实例或对象可以通过多种不同的方式进行引用和访问。



== 对象访问路径

总体而言，访问对象时有两种路径类型：

* 主卷
+
对象是 API 调用的主目标或直接目标。

* 外部
+
此对象不是 API 调用的主要引用，而是从主对象链接到。因此，它是一个外部或下游对象，并通过主对象中的字段进行引用。





== 使用 UUID 访问对象

创建每个对象时，系统会为其分配一个唯一标识符，在大多数情况下，此标识符为 128 位 UUID 。分配的 UUID 值是不可更改的，在 ONTAP 内部使用这些值来访问和管理资源。因此， UUID 通常可提供最快，最稳定的对象访问方式。

对于许多资源类型，可以在 URL 中的路径密钥中提供 UUID 值来访问特定对象。例如，您可以使用以下命令访问节点实例： `` /cluster/nodes/｛ uuid ｝`



== 使用对象属性访问对象

除了 UUID 之外，您还可以使用对象属性访问对象。在大多数情况下，使用 name 属性非常方便。例如，您可以在 URL 字符串中使用以下查询参数来按名称访问节点实例： ` /cluster/nodes ？ name=node_one` 。除了查询参数之外，还可以通过主对象中的属性访问外部对象。

虽然您可以使用名称或其他属性来访问对象，而不是 UUID ，但可能存在以下几个缺点：

* 名称字段不可更改，可以更改。如果在访问对象之前更改了某个对象的名称，则返回的对象将不正确，或者对象访问错误将失败。
+

NOTE: 此问题描述可以在外部对象上使用 POST 或修补方法，也可以在主对象上使用 GET 方法。

* ONTAP 必须将名称字段转换为相应的 UUID 。这是一种间接访问，可以成为性能问题描述。


特别是，如果满足以下一项或多项条件，则性能可能会下降：

* 使用 GET 方法
* 访问大量对象
* 使用复杂或精细的查询




== 集群与 SVM 环境

有多个 REST 端点同时支持集群和 SVM 。使用其中一个端点时，您可以通过 `sCOP=[SVM| 集群 ]` 值指示 API 调用的上下文。支持双环境的端点示例包括 IP 接口和安全角色。


NOTE: 范围值基于为每个 API 调用提供的属性具有默认值。



== 对一组对象使用修补程序和删除

在资源实例上支持修补或删除的每个 REST 端点也支持对一组对象使用相同的方法。唯一的要求是，必须通过 URL 字符串中的查询参数至少提供一个字段。在对集合发出修补程序或进行删除时，这相当于在内部执行以下操作：

* 基于查询的 GET 以检索收集
* 对集合中的每个对象执行的修补或删除调用的序列


操作超时可通过 `return_timeout` 设置，默认值为 15 秒。如果在超时之前未完成，则响应将包含指向下一个对象的链接。您必须使用下一个链接重新发出相同的 HTTP 方法才能继续此操作。
