---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: operation, request and response, crud 
summary: 您可以通过多种不同方式访问 ONTAP REST API 。 
---
= 基本操作特征
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
虽然 REST 建立了一组通用的技术和最佳实践，但每个 API 的详细信息可能因设计选择而异。



== 请求和响应 API 事务

每个 REST API 调用都作为 HTTP 请求执行给 ONTAP 系统，该系统会向客户端生成关联的响应。此请求 / 响应对被视为 API 事务。在使用 API 之前，您应熟悉可用于控制请求的输入变量以及响应输出的内容。



== 支持 CRUD 操作

通过 ONTAP REST API 提供的每个资源均可根据 CRUD 模型进行访问：

* 创建
* 读取
* 更新
* 删除


对于某些资源，仅支持部分操作。有关每个资源的详细信息，您应查看 ONTAP 集群上的 ONTAP API 文档页面。



== 对象标识符

创建每个资源实例或对象时，系统会为其分配一个唯一标识符。在大多数情况下，标识符为 128 位 UUID 。这些标识符在特定 ONTAP 集群中具有全局唯一性。发出创建新对象实例的 API 调用后，将在 HTTP 响应的位置标题中向调用方返回一个具有关联 ID 值的 URL 。在引用资源实例时，您可以提取此标识符并在后续调用中使用它。


NOTE: 对象标识符的内容和内部结构可以随时更改。仅当引用关联对象时，才应根据需要在适用的 API 调用上使用标识符。



== 对象实例和集合

根据资源路径和 HTTP 方法， API 调用可以应用于特定对象实例或对象集合。



== 同步和异步操作

ONTAP 可通过两种方式执行从客户端收到的 HTTP 请求。

同步处理:: ONTAP 会立即执行此请求，如果成功，则会使用 HTTP 状态代码 200 或 201 进行响应。
+
--
使用 GET ， HEAD 和 OPTIONS 方法的每个请求始终会同步执行。此外，如果使用 POST ，修补和删除的请求预计在两秒内完成，则这些请求会同步运行。

--
异步处理:: 如果异步请求有效， ONTAP 将创建一个后台任务来处理此请求，并创建一个作业对象来锁定此任务。202 HTTP 状态将与作业对象一起返回给调用程序。要确定最终成功还是失败，您必须检索作业的状态。
+
--
如果使用 POST ，修补和删除方法的请求预计需要超过两秒才能完成，则这些请求会异步运行。


NOTE: `return_timeout` query 参数可用于异步 API 调用，并且可以将异步调用同步转换为完成。有关详细信息，请参见 `如何使用作业对象进行异步处理` 。

--




== 安全性

REST API 提供的安全性主要基于 ONTAP 提供的现有安全功能。API 使用以下安全性：

* 传输层安全性
+
ONTAP LIF 与客户端之间通过网络发送的所有流量通常会根据 ONTAP 配置设置使用 TLS 进行加密。

* 客户端身份验证
+
ONTAP System Manager 和网络易管理性 SDK 提供的相同身份验证选项也可用于 ONTAP REST API 。

* HTTP 身份验证
+
在 HTTP 级别， API 事务使用基本身份验证。每个请求都会添加一个 HTTP 标头，其中用户名和密码包含在 base64 字符串中。

* ONTAP 授权
+
ONTAP 实施基于角色的授权模式。访问 ONTAP REST API 或 API 文档页面时使用的帐户应具有适当的权限。


